#!/bin/bash
set -e

# Check if cargo is installed
if ! command -v cargo &> /dev/null; then
    echo "cargo is not installed. Please install it from https://rustup.rs/"
    # install cargo
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi



cd cli/src && cargo build --release
