#!/bin/bash
DEV_SETUP=./cli/target/release/tranquility
tranquility() {
  echo "Running tranquility..."
    $DEV_SETUP
}
# Check if the tranquility executable exists
if [ ! -f $DEV_SETUP ]; then
  echo "Error: tranquility executable not found. Runing the './build' command."
  ./build
fi

tranquility