#!/bin/bash

DEV_SETUP=./cli/target/release/tranquility

tranquility() {
  echo "Running tranquility..."
  $DEV_SETUP "$@"
}

# Check if the tranquility executable exists
if [ ! -f "$DEV_SETUP" ]; then
  echo "Error: tranquility executable not found. Running the './build' command."
  ./build
fi

# Call tranquility with passed arguments
tranquility "$@"
