#!/bin/bash
DEV_SETUP=./cli/target/release/devsetup
devsetup() {
  echo "Running devsetup..."
    $DEV_SETUP
}
# Check if the devsetup executable exists
if [ ! -f $DEV_SETUP ]; then
  echo "Error: devsetup executable not found. Please run './build' first."
  exit 1
fi

devsetup