// src/categories.rs

use clap::ValueEnum;

/// Software categories
#[derive(Copy, Clone, Debug, PartialEq, Eq, ValueEnum)]
pub enum Category {
    Fonts,
    PackageManagement,
    Shells,
    Browsers,
    Servers,
    TerminalEmmulators,
    PasswordManagement,
    Encyption,
    RemoteDesktop,
    VPN,
    DownloadMangement,
    Imaging,
    WindowManagement,
    CLITools,
    Customization,
    Communication,
    Creative,
    Productivity,
    Utilities,
    Office,
    OfficeAddons,
    NoteTaking,
    TaskManagement,
    Virtualization,
    Gaming,
    Networking,
    Essential,
    Development,
    Recording,
    Streaming,
    DatabasesManagement,
    ProgrammingLanguages,
    Editors,
    Containerization,
    Engines,
    AI,
    DevTools,
}